### ISSUE TITLE
Drop rustc-serialize dependency

### ISSUE THREAD

**Issue by dtolnay** [neil-lobracco/twilio-rs#12]
It has been deprecated: [announcement](https://users.rust-lang.org/t/deprecation-of-rustc-serialize/10485?u=dtolnay).

Is there any functionality you would require from Serde or another library before this would be possible?

**Comment by lancecarlson** [comment]
@dtolnay I haven't investigated how easy this would be to do. Can I just remove it from Cargo you think? I may dig in but not any time soon.

**Comment by dtolnay** [comment]
It is not just a matter of removing it from Cargo.toml. The code is using it [here](https://github.com/neil-lobracco/twilio-rs/blob/031360fcf902c944b488f5748177a36d52c423db/src/webhook.rs#L40) and [here](https://github.com/neil-lobracco/twilio-rs/blob/d04b04deff73b541fb76824791021fd38e1b320f/src/lib.rs#L84) so you would need to replace those with a different library, probably a combination of [`data-encoding`](https://crates.io/crates/data-encoding) and [Serde](https://serde.rs/) both of which are stable and actively maintained.

**Comment by lancecarlson** [comment]
@dtolnay I did this btw.

https://github.com/neil-lobracco/twilio-rs/commit/ec76084c8fc295b1f607a36ac0abc19fc84d50a8
