### ISSUE TITLE
Tokio 1.0 migration error

### ISSUE THREAD

**Issue by jayhuang75** [neil-lobracco/twilio-rs#27]
Hello team,

I would like to bring to your attention that since Tokio has the update to 1.0.  This package will no longer work. 

Is there any roadmap update this?

Thank you.

**Comment by sazzle2611** [comment]
I've just run into this as well, I'm using mysql_async which requires tokio 1.0

Thanks

**Comment by jayhuang75** [comment]
@sazzle2611, I have managed this buy fork and update the package. and have been raised a [pull request](https://github.com/neil-lobracco/twilio-rs/pull/29). 

If you want to use it before the pull request has been accepted. You can add this to your cargo.toml
`twilio = { git = "https://github.com/jayhuang75/twilio-rs" }`

Please note, I just simply update some versions, which may or may not impact your current project.

**Comment by sazzle2611** [comment]
Thank you @jayhuang75 

I've set it up with your fork and it's working perfectly :)

**Comment by jayhuang75** [comment]
@sazzle2611 happy this can help you.

**Comment by EvanCarroll** [comment]
Why did you close this issue... It's still an issue until your patch is accepted.
