### ISSUE TITLE
Warning on compilation noticed - Dependency rustc-serialize (rust-crypto)

### ISSUE THREAD

**Issue by JeffLabonte** [neil-lobracco/twilio-rs#37]
Hello!

I noticed I had a warning in my command line when working on one of my [projects](https://github.com/JeffLabonte/Baby-Bottle-Temperature-Monitor). I investigated a little bit to find what dependency is guilty. It turns out this project uses [rust-crypto](https://github.com/DaGenix/rust-crypto/). 

`Rust-Crypto` is not maintained anymore. Clearly the owner doesn't want to deal with it anymore, [here is what I found in the project's  PRs](https://github.com/DaGenix/rust-crypto/pulls?q=is%3Apr+is%3Aopen+rustc-serialize) and [this is what I found in the discussions](https://github.com/DaGenix/rust-crypto/issues/458)

Below is the JSON report cargo generated. I compressed it into a zip:
[future-incompat-report.zip](https://github.com/neil-lobracco/twilio-rs/files/11135940/future-incompat-report.zip)

**Comment by neil-lobracco** [comment]
Hey, closing this out - version `1.0.3` has moved off this unmaintained library.
